### ISSUE TITLE
Getting class not found on decryption of env variables

### ISSUE THREAD

**Issue by abhijeet9920** [BaglerIT/envariable#1]
Hi, I'm using your package for my Laravel version 5.2.45. I encrypted my env variables using console command, and for decrypt I've added

`$crypt = new Illuminate\Encryption\Encrypter(env('APP_KEY'));
...
'mysql' => [
   'driver'    => 'mysql',
   'host'      => $crypt->decrypt(env('DB_HOST')),
   'database'  => $crypt->decrypt(env('DB_DATABASE')),
   'username'  => $crypt->decrypt(env('DB_USERNAME')),
   'password'  => $crypt->decrypt(env('DB_PASSWORD')),
   'port'      => $crypt->decrypt(env('DB_PORT')),
   ...`

into database.php, but I'm getting error telling
`Uncaught exception 'ReflectionException' with message 'Class log does not exist' in /var/www/html/laraveljwt/vendor/laravel/framework/src/Illuminate/Container/Container.php:734.` Can you tell me where I'm doing mistake. Thank you

**Comment by DaveBagler** [comment]
It may mean that you're using `Log::something` rather than `\Log::something` somewhere in your code.
